writer1 = rolling file
writer1.file = exec_{date: yyyy-MM-dd}_log_{count}.log
writer1.policies = startup, daily: 07:00
writer1.format = {date: HH:mm:ss} [{thread}] {level}: {message}
writer1.append = true
